'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, CircleDot, Columns3, Filter, List, Plus, Save, Trash2, X } from 'lucide-react'
import type { IssuePriority, IssueStatus, WorkIssue } from '@/features/simulator/domain/issues'

type Props = {
  issues: WorkIssue[]
  createIssue: (issue: Omit<WorkIssue, 'id' | 'updatedAt'>) => void
  updateIssue: (issue: WorkIssue) => void
  openWorkspace: () => void
}

const columns: { id: IssueStatus; label: string }[] = [{ id: 'todo', label: 'To do' }, { id: 'in_progress', label: 'In progress' }, { id: 'in_review', label: 'In review' }, { id: 'done', label: 'Done' }]
const people: Record<WorkIssue['assignee'], string> = { alex: 'Alex Morgan', maya: 'Maya Chen', noah: 'Noah Patel', adele: 'Adele Okafor', devon: 'Devon Reeves' }
const statusLabel: Record<IssueStatus, string> = { todo: 'To do', in_progress: 'In progress', in_review: 'In review', done: 'Done', blocked: 'Blocked' }

function IssueCard({ issue, onOpen, onStatus }: { issue: WorkIssue; onOpen: () => void; onStatus: (status: IssueStatus) => void }) {
  return <article className="live-issue-card" onClick={onOpen}><div className="live-issue-top"><span className={`status-dot ${issue.status === 'blocked' ? 'blocked' : issue.status === 'in_review' ? 'review' : issue.status === 'done' ? 'done' : ''}`} /><small>{issue.id}</small><select aria-label={`Move ${issue.id}`} value={issue.status} onClick={(event) => event.stopPropagation()} onChange={(event) => onStatus(event.target.value as IssueStatus)}>{columns.map((column) => <option value={column.id} key={column.id}>{column.label}</option>)}<option value="blocked">Blocked</option></select></div><h3>{issue.title}</h3><p>{issue.description}</p><div className="live-issue-footer"><span className={`pill ${issue.priority === 'high' ? 'coral-pill' : issue.priority === 'low' ? 'muted-pill' : 'sky-pill'}`}>{issue.priority.toUpperCase()}</span><span>{issue.estimate} pts</span><span className="assignee-chip">{people[issue.assignee].split(' ').map((part) => part[0]).join('')}</span></div></article>
}

export default function FunctionalIssuesView({ issues, createIssue, updateIssue, openWorkspace }: Props) {
  const [layout, setLayout] = useState<'board' | 'list'>('board')
  const [priority, setPriority] = useState<'all' | IssuePriority>('all')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [isCreating, setIsCreating] = useState(false)
  const [newTitle, setNewTitle] = useState('')
  const [newPriority, setNewPriority] = useState<IssuePriority>('medium')
  const [criterion, setCriterion] = useState('')
  const selected = issues.find((issue) => issue.id === selectedId) || null
  const visibleIssues = useMemo(() => issues.filter((issue) => priority === 'all' || issue.priority === priority), [issues, priority])
  const makeIssue = () => {
    if (newTitle.trim().length < 4) return
    createIssue({ title: newTitle.trim(), description: 'Add business context and an implementation note.', status: 'todo', priority: newPriority, assignee: 'alex', estimate: 2, sprint: 'Sprint 2', acceptanceCriteria: ['Define an observable acceptance criterion'], dependencyIds: [] })
    setNewTitle(''); setNewPriority('medium'); setIsCreating(false)
  }
  const saveSelected = (changes: Partial<WorkIssue>) => selected && updateIssue({ ...selected, ...changes, updatedAt: 'just now' })
  return <div className="page live-issues-page"><section className="page-title"><div><p className="eyebrow">SPRINT 2 · SEPT 16–27</p><h1>Product usage</h1><p>Create, prioritize, and move work while keeping dependencies and acceptance criteria visible.</p></div><button className="primary-button" onClick={() => setIsCreating(true)}><Plus size={16} /> New issue</button></section>
    <div className="issue-controls"><div className="tabs"><button className={layout === 'board' ? 'selected' : ''} onClick={() => setLayout('board')}><Columns3 size={14} /> Board</button><button className={layout === 'list' ? 'selected' : ''} onClick={() => setLayout('list')}><List size={14} /> All issues</button></div><label className="issue-filter"><Filter size={14} /> Priority<select value={priority} onChange={(event) => setPriority(event.target.value as 'all' | IssuePriority)}><option value="all">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label></div>
    {isCreating && <section className="new-issue-panel"><div><span className="eyebrow">NEW ISSUE</span><input autoFocus value={newTitle} onChange={(event) => setNewTitle(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && makeIssue()} placeholder="Describe the work to be done"/></div><select value={newPriority} onChange={(event) => setNewPriority(event.target.value as IssuePriority)}><option value="high">High priority</option><option value="medium">Medium priority</option><option value="low">Low priority</option></select><button className="primary-button" onClick={makeIssue}><Check size={15} /> Create</button><button className="plain-close" onClick={() => setIsCreating(false)}><X size={16} /></button></section>}
    {layout === 'board' ? <div className="live-board">{columns.map((column) => <section className="live-board-column" key={column.id}><div className="column-head"><b>{column.label}</b><span>{visibleIssues.filter((issue) => issue.status === column.id).length}</span></div>{visibleIssues.filter((issue) => issue.status === column.id).map((issue) => <IssueCard key={issue.id} issue={issue} onOpen={() => setSelectedId(issue.id)} onStatus={(status) => updateIssue({ ...issue, status, updatedAt: 'just now' })}/>)}</section>)}</div> : <div className="issues-table">{visibleIssues.map((issue) => <button key={issue.id} onClick={() => setSelectedId(issue.id)}><span className={`status-dot ${issue.status === 'done' ? 'done' : issue.status === 'in_review' ? 'review' : ''}`}/><b>{issue.id}</b><strong>{issue.title}</strong><span className={`pill ${issue.priority === 'high' ? 'coral-pill' : 'sky-pill'}`}>{issue.priority}</span><span>{statusLabel[issue.status]}</span><span>{people[issue.assignee]}</span><ArrowRight size={15}/></button>)}</div>}
    {selected && <div className="issue-drawer-backdrop" onMouseDown={() => setSelectedId(null)}><aside className="issue-drawer" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-head"><div><span className="issue-id">{selected.id}</span><h2>{selected.title}</h2></div><button className="plain-close" onClick={() => setSelectedId(null)}><X size={18}/></button></div><label>Title<input value={selected.title} onChange={(event) => saveSelected({ title: event.target.value })}/></label><label>Description<textarea value={selected.description} onChange={(event) => saveSelected({ description: event.target.value })}/></label><div className="drawer-selects"><label>Status<select value={selected.status} onChange={(event) => saveSelected({ status: event.target.value as IssueStatus })}>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Priority<select value={selected.priority} onChange={(event) => saveSelected({ priority: event.target.value as IssuePriority })}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Assignee<select value={selected.assignee} onChange={(event) => saveSelected({ assignee: event.target.value as WorkIssue['assignee'] })}>{Object.entries(people).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label><label>Estimate<input type="number" min="1" max="13" value={selected.estimate} onChange={(event) => saveSelected({ estimate: Number(event.target.value) || 1 })}/></label></div><div className="criteria-editor"><span className="eyebrow">ACCEPTANCE CRITERIA</span>{selected.acceptanceCriteria.map((item, index) => <div key={`${item}-${index}`}><Check size={14}/><input value={item} onChange={(event) => { const next = [...selected.acceptanceCriteria]; next[index] = event.target.value; saveSelected({ acceptanceCriteria: next }) }}/><button onClick={() => saveSelected({ acceptanceCriteria: selected.acceptanceCriteria.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={14}/></button></div>)}<div className="add-criterion"><input value={criterion} onChange={(event) => setCriterion(event.target.value)} placeholder="Add acceptance criterion"/><button onClick={() => { if (criterion.trim()) { saveSelected({ acceptanceCriteria: [...selected.acceptanceCriteria, criterion.trim()] }); setCriterion('') } }}>Add</button></div></div><div className="dependency-editor"><span className="eyebrow">DEPENDENCIES</span><p>{selected.dependencyIds.length ? selected.dependencyIds.join(', ') : 'No blocking dependencies'}</p></div><div className="drawer-actions"><button className="primary-button" onClick={() => { updateIssue({ ...selected, updatedAt: 'just now' }); setSelectedId(null) }}><Save size={15}/> Save changes</button><button className="ghost-button" onClick={openWorkspace}>Open workspace <ArrowRight size={14}/></button></div></aside></div>}
  </div>
}
